<?php
    $members = [
        [
            'name'=>'Andrew Oneal',
            'title'=>'ASE Student',
            'year'=>'2',
            'image'=>'assets\images\AndrewHeadshot.jpg',
            'profession'=>'Software Engineer',
            'company'=>'Spotify',
            'email'=>'oneala5@nku.edu',
            'intro'=>'Hello! I am a sophomore in the Applied Software Engineering program. I am minoring in Philosophy. I am very focused on self-improvement and self-fulfillment. I love working on myself and getting better at everything that I do.',
            'quote'=>'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment. - Marcus Aurelius',
            'funfact'=>'I am obsessed with hobbies. I am usually engrossed in 2-3 hobbies at a time and I switch them around every year or so. My current hobbies are electric guitar, social media creation, and studying philosophy. Some hobbies I want to get into in the future are motorcycles, car mods, robotics,  and video editing among many others.',
            'progressTitle1'=>'Programming',
            'progressTitle2'=>'Typing',
            'progressTitle3'=>'Technical Writing',
            'progressPercent1'=>'70',
            'progressPercent2'=>'80',
            'progressPercent3'=>'85',
            'dob'=>'2002-09-09'
        ],
        [
            'name'=>'Geoff McGollum',
            'title'=>'CIT Student',
            'year'=>'3',
            'image'=>'assets\images\Geoff.jpg',
            'profession'=>'Information Scientist',
            'company'=>'Thermo Fisher',
            'email'=>'geoff@jeff.com',
            'intro'=>'Hi I\'m Geoff! I like information and science!',
            'quote'=>'Yeah! Science! - Jesse Pinkman',
            'funfact'=>'I have watched the entirety of Breaking Bad in one sitting... twice.',
            'progressTitle1'=>'Chemistry',
            'progressTitle2'=>'Sales',
            'progressTitle3'=>'Management',
            'progressPercent1'=>'70',
            'progressPercent2'=>'80',
            'progressPercent3'=>'85',
            'dob'=>'1956-03-07'
        ],
        [
            'name'=>'Franklin Gibbs',
            'title'=>'CSC Student',
            'year'=>'1',
            'image'=>'assets\images\FranklinHeadshot.jpg',
            'profession'=>'Front-End Developer',
            'company'=>'Facebook',
            'email'=>'franklin@bateman.org',
            'intro'=>'Hi I\'m Franklin! I like computers and science!',
            'quote'=>'Sometimes the road less traveled is less traveled for a reason. - Jerry Seinfeld',
            'funfact'=>'I have watched the entirety of Seinfeld in one sitting... twice.',
            'progressTitle1'=>'Comedy',
            'progressTitle2'=>'HTML/CSS',
            'progressTitle3'=>'Javascript',
            'progressPercent1'=>'70',
            'progressPercent2'=>'80',
            'progressPercent3'=>'85',
            'dob'=>'1954-04-29'
        ],
    ];
?>